// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiMXxELmnUNn8NbpEe885DzhXgtMCNEbI',
    appId: '1:482423255035:web:36140c3bc7a6ca1424a55e',
    messagingSenderId: '482423255035',
    projectId: 'homeservice-8c000',
    authDomain: 'homeservice-8c000.firebaseapp.com',
    storageBucket: 'homeservice-8c000.firebasestorage.app',
    measurementId: 'G-8DJ8GRBN12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChQ8tMAphKjFgsF18vcUEL-32NlfbT7cY',
    appId: '1:482423255035:android:193fe4d9cf0b14e524a55e',
    messagingSenderId: '482423255035',
    projectId: 'homeservice-8c000',
    storageBucket: 'homeservice-8c000.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzEY5VDc6Xy9c_TyzjF6Mht-6kMGj2fKY',
    appId: '1:482423255035:ios:e04ed0c56900741724a55e',
    messagingSenderId: '482423255035',
    projectId: 'homeservice-8c000',
    storageBucket: 'homeservice-8c000.firebasestorage.app',
    iosClientId: '482423255035-daglqfp7ct4i1cjiaih4nviguq2ldhje.apps.googleusercontent.com',
    iosBundleId: 'com.helloteen.helloTeen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzEY5VDc6Xy9c_TyzjF6Mht-6kMGj2fKY',
    appId: '1:482423255035:ios:e04ed0c56900741724a55e',
    messagingSenderId: '482423255035',
    projectId: 'homeservice-8c000',
    storageBucket: 'homeservice-8c000.firebasestorage.app',
    iosClientId: '482423255035-daglqfp7ct4i1cjiaih4nviguq2ldhje.apps.googleusercontent.com',
    iosBundleId: 'com.helloteen.helloTeen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrwU9qY_qSumcf2zaoikE2NgQk0bUPq5Y',
    appId: '1:482423255035:web:3a5d2f16fff06f3924a55e',
    messagingSenderId: '482423255035',
    projectId: 'homeservice-8c000',
    authDomain: 'homeservice-8c000.firebaseapp.com',
    storageBucket: 'homeservice-8c000.firebasestorage.app',
    measurementId: 'G-DKFTPLYFRT',
  );
}
